name: Deploy blog

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish blog contents
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract built files
        run: |
          chmod +x ./copy.sh
          ./copy.sh
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: ente-web
          directory: ./out/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
